
export default new Map([
["src/data/programming/blockchain-in-2025.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fprogramming%2Fblockchain-in-2025.mdx&astroContentModuleFlag=true")],
["src/data/programming/how-i-built-my-blog.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fprogramming%2Fhow-i-built-my-blog.mdx&astroContentModuleFlag=true")],
["src/data/programming/programming-kedua-saya.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fprogramming%2Fprogramming-kedua-saya.mdx&astroContentModuleFlag=true")],
["src/data/programming/programming-pertama-saya.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fprogramming%2Fprogramming-pertama-saya.mdx&astroContentModuleFlag=true")],
["src/data/programming/programming-ketiga-saya.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fprogramming%2Fprogramming-ketiga-saya.mdx&astroContentModuleFlag=true")],
["src/data/programming/web-development-in-2025.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fprogramming%2Fweb-development-in-2025.mdx&astroContentModuleFlag=true")],
["src/data/general/mystery-of-time/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fgeneral%2Fmystery-of-time%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/general/postingan-kedua-saya/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fgeneral%2Fpostingan-kedua-saya%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/movies/18-x-2-beyond-youthful-days/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fmovies%2F18-x-2-beyond-youthful-days%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/general/postingan-pertama-saya/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fgeneral%2Fpostingan-pertama-saya%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/movies/our-little-sister/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fmovies%2Four-little-sister%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/general/postingan-ketiga-saya/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fgeneral%2Fpostingan-ketiga-saya%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/movies/still-walking/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fmovies%2Fstill-walking%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/movies/perfect-days/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fmovies%2Fperfect-days%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/movies/18-x-2-beyond-youthful-days/comments/1764860818748.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fmovies%2F18-x-2-beyond-youthful-days%2Fcomments%2F1764860818748.mdx&astroContentModuleFlag=true")],
["src/data/general/mystery-of-time/comments/1764860440737.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fgeneral%2Fmystery-of-time%2Fcomments%2F1764860440737.mdx&astroContentModuleFlag=true")]]);
		