// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Blog = Collections['blogs']['schema']['_output']
export declare const blogs: Blog[]

export type Programming = Collections['programmings']['schema']['_output']
export declare const programmings: Programming[]

export type Movie = Collections['movies']['schema']['_output']
export declare const movies: Movie[]
