import type { Metadata } from "next";
import localFont from "next/font/local";
import { globalCss } from "@pigment-css/react";
import Navbar from "@/components/Navbar";
import "@pigment-css/react/styles.css";

const globalStyle = globalCss`
*,
::before,
::after {
	box-sizing: border-box;
}

html {
	font-family:
		system-ui,
		'Segoe UI',
		Roboto,
		Helvetica,
		Arial,
		sans-serif,
		'Apple Color Emoji',
		'Segoe UI Emoji';
	line-height: 1.15;
	-webkit-text-size-adjust: 100%;
	tab-size: 4;
}

body {
	margin: 0;
}

b,
strong {
	font-weight: bolder;
}

code,
kbd,
samp,
pre {
	font-family:
		ui-monospace,
		SFMono-Regular,
		Consolas,
		'Liberation Mono',
		Menlo,
		monospace; 
	font-size: 1em;
}


small {
	font-size: 80%;
}


sub,
sup {
	font-size: 75%;
	line-height: 0;
	position: relative;
	vertical-align: baseline;
}

sub {
	bottom: -0.25em;
}

sup {
	top: -0.5em;
}

table {
	border-color: currentcolor;
}

button,
input,
optgroup,
select,
textarea {
	font-family: inherit; 
	font-size: 100%;
	line-height: 1.15;
	margin: 0;
}

button,
[type='button'],
[type='reset'],
[type='submit'] {
	-webkit-appearance: button;
}

legend {
	padding: 0;
}

progress {
	vertical-align: baseline;
}

::-webkit-inner-spin-button,
::-webkit-outer-spin-button {
	height: auto;
}


[type='search'] {
	-webkit-appearance: textfield; /* 1 */
	outline-offset: -2px; /* 2 */
}


::-webkit-search-decoration {
	-webkit-appearance: none;
}

::-webkit-file-upload-button {
	-webkit-appearance: button; /* 1 */
	font: inherit; /* 2 */
}

summary {
	display: list-item;
}
`;

const inter = localFont({
  src: [
    {
      path: "../InterVariable.woff2",
      style: "normal",
    },
    {
      path: "../InterVariable-Italic.woff2",
      style: "italic",
    },
  ],
  variable: "--font-inter",
});

const jakartaSans = localFont({
  src: [
    {
      path: "../PlusJakartaSans-Regular.woff2",
      style: "normal",
    },
    {
      path: "../PlusJakartaSans-Italic.woff2",
      style: "italic",
    },
  ],
  variable: "--font-jakarta-sans",
});

const uncutSans = localFont({
  src: [
    {
      path: "../UncutSans-Light.woff2",
      weight: "300", //light
      style: "normal",
    },
    {
      path: "../UncutSans-LightItalic.woff2",
      weight: "300", //light italic
      style: "italic",
    },
    {
      path: "../UncutSans-Book.woff2",
      weight: "350", //book
      style: "normal",
    },
    {
      path: "../UncutSans-BookItalic.woff2",
      weight: "350", //book italic
      style: "italic",
    },
    {
      path: "../UncutSans-Regular.woff2",
      weight: "400", //regular
      style: "normal",
    },
    {
      path: "../UncutSans-RegularItalic.woff2",
      weight: "400", //regular italic
      style: "italic",
    },
    {
      path: "../UncutSans-Medium.woff2",
      weight: "500", //medium
      style: "normal",
    },
    {
      path: "../UncutSans-MediumItalic.woff2",
      weight: "500", //medium italic
      style: "italic",
    },
    {
      path: "../UncutSans-Semibold.woff2",
      weight: "600", //semibold
      style: "normal",
    },
    {
      path: "../UncutSans-SemiboldItalic.woff2",
      weight: "600", //semibold italic
      style: "italic",
    },
    {
      path: "../UncutSans-Bold.woff2",
      weight: "700", //bold
      style: "normal",
    },
    {
      path: "../UncutSans-BoldItalic.woff2",
      weight: "700", //bold italic
      style: "italic",
    },
  ],
  variable: "--font-uncut-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={globalStyle}>
      <body className={`${uncutSans} ${inter} ${jakartaSans}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
